[package]
name = "expression_parser"
version = "0.1.0"
authors = ["Robert Pirtle <astropirtle@gmail.com>"]
edition = "2018"

[lib]
name = "expression_parser"
path = "src/lib.rs"

[[bin]]
name = "parser"
path = "src/bin.rs"
